[package]
name = "pdb-import-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "^1.0"
binaryninja = {path = "../../"}
home = "^0.5.5"
itertools = "^0.11"
log = "^0.4"
pdb = "^0.8"
cab = "^0.4"
regex = "1"

[features]
demo = []

[profile.release]
debug = 1
